/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksRecipeMaintenanceRouteImport } from './routes/api/public/hooks/recipe-maintenance'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRecipeMaintenanceRoute =
  ApiPublicHooksRecipeMaintenanceRouteImport.update({
    id: '/api/public/hooks/recipe-maintenance',
    path: '/api/public/hooks/recipe-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/planner': typeof PlannerRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/recipe-maintenance': typeof ApiPublicHooksRecipeMaintenanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/planner': typeof PlannerRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/recipe-maintenance': typeof ApiPublicHooksRecipeMaintenanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/planner': typeof PlannerRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/recipe-maintenance': typeof ApiPublicHooksRecipeMaintenanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/planner'
    | '/settings'
    | '/api/public/hooks/recipe-maintenance'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/planner' | '/settings' | '/api/public/hooks/recipe-maintenance'
  id:
    | '__root__'
    | '/'
    | '/planner'
    | '/settings'
    | '/api/public/hooks/recipe-maintenance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlannerRoute: typeof PlannerRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicHooksRecipeMaintenanceRoute: typeof ApiPublicHooksRecipeMaintenanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recipe-maintenance': {
      id: '/api/public/hooks/recipe-maintenance'
      path: '/api/public/hooks/recipe-maintenance'
      fullPath: '/api/public/hooks/recipe-maintenance'
      preLoaderRoute: typeof ApiPublicHooksRecipeMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlannerRoute: PlannerRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicHooksRecipeMaintenanceRoute: ApiPublicHooksRecipeMaintenanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
